version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
  generate_notebook:
    run: jupyter:latest jupyter nbconvert  /workspace/analysis/analysis.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400

    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        notebook: output/analysis.html 
        figures: output/figures/*
          
