version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv
  
  generate_notebook:
    run: jupyter:latest jupyter nbconvert  /workspace/analysis/analysis.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400

    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
        notebook: output/analysis.html 
          
  input_counts:
      run: python:latest python analysis/input_counts.py
      needs: [generate_study_population]
      outputs:
        moderately_sensitive:
          cohort: output/inputcounts.txt

  generate_study_population_all:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_exclusioncounts
    outputs:
      highly_sensitive:
        cohort: output/input_exclusioncounts.csv

  exclusion_counts:
      run: python:latest python analysis/exclusion_counts.py
      needs: [generate_study_population_all]
      outputs:
        moderately_sensitive:
          cohort: output/exclusioncounts.txt
  
  generate_exclusion_notebook:
    run: jupyter:latest jupyter nbconvert  /workspace/analysis/exclusion_counts.ipynb --execute --to html --output-dir=/workspace/output --ExecutePreprocessor.timeout=86400
    needs: [generate_study_population_all]
    outputs:
      moderately_sensitive:
        notebook: output/exclusion_counts.html